### ISSUE TITLE
When click on check box, how to get feedback?

### ISSUE THREAD

**Issue by zhw511006** [Boris-Em/BEMCheckBox#1]
Do we have a method that can get feedback when click on checkbox? Thanks!

**Comment by Boris-Em** [comment]
Hi @zhw511006, 
There is currently no way of getting feedback other than using KVO.
We could implement a delegate method that also takes into account the animation.

**Comment by Boris-Em** [comment]
I just implemented a delegate method that takes care of giving feedback for events. It's available with the version [1.1.0](https://github.com/Boris-Em/BEMCheckBox/releases/tag/1.1.0) of **BEMCheckBox**.
Thank you for opening this issue.

Closed as fixed with v1.1.0.

**Comment by zhw511006** [comment]
It works! Thanks!
