### ISSUE TITLE
"-[UIView setOn:]: unrecognized selector sent to instance 0x7fa355e28390"

### ISSUE THREAD

**Issue by sodiqOladeni** [Boris-Em/BEMCheckBox#100]
Error while using in TableView with Custom tableView Cell, the BEMCheckBox was connected from storyboard

**Comment by Boris-Em** [comment]
We will need a bit more info in order to debug this problem. 
I'm closing this issue in the meantime. 
If you're still experiencing this issue, please re-open this issue and give us more to work with!
