### ISSUE TITLE
Is there "enabled" property or equivalent?

### ISSUE THREAD

**Issue by rwforsythe** [Boris-Em/BEMCheckBox#11]
I want to display the state of the checkbox, but not allow the user to change the state. Doesn't seem to be a property or a way of canceling the action via a delegate.

**Comment by Boris-Em** [comment]
Hi @rwforsythe, 
Have you tried the property `userInteractionEnabled` ?
  
Something like that:
```objective-c
self.checkBox.userInteractionEnabled = NO;
```
