### ISSUE TITLE
Square checkbox of size less than 20 x 20 px appears distorted

### ISSUE THREAD

**Issue by hunaid-hassan-confiz** [Boris-Em/BEMCheckBox#13]
![checked](https://cloud.githubusercontent.com/assets/13764896/11930420/01bf3fa2-a805-11e5-9385-94c670f52673.png)
![unchecked](https://cloud.githubusercontent.com/assets/13764896/11930421/01c01eea-a805-11e5-9dda-929a50e2e8f2.png)

Testing environment: iOS 9.1 iPhone 6 with latest version of library

**Comment by Boris-Em** [comment]
Closed as fixed with 063228651afb0f87f24c479b1106c6f48fb74fa8.
