### ISSUE TITLE
OS X version

### ISSUE THREAD

**Issue by akac** [Boris-Em/BEMCheckBox#16]
I've made an OS X version - at first I was using #ifdefs to keep one code between iOS and OS X, but I had a weird Xcode issue that had me junk that. 

If you'd like it, let me know and I'll fork it and put it up.

**Comment by Boris-Em** [comment]
Hi @akac,
That could actually be very interesting. Let me know if you can make it available!
Boris.

**Comment by ZHANGneuro** [comment]
https://github.com/ZHANGneuro/CenCheckbox
