### ISSUE TITLE
Xcode warnning: Failed to set (lineWidth) user defined inspected property on (UIView)

### ISSUE THREAD

**Issue by mtide** [Boris-Em/BEMCheckBox#18]
Hello @Boris-Em , I got an error: 
Failed to set (lineWidth) user defined inspected property on (UIView): [ setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key lineWidth.

I initialize the BECheckBox using Interface Builder. All I do is just follow the readme steps. 
Thank you!!

**Comment by niukaiquan** [comment]
I got it too

**Comment by Boris-Em** [comment]
@mtide, have you found a fix for this? I haven't been able to repro it.
If you're still experiencing this bug, would you mind posting detailed repro steps here?
Thanks!
