### ISSUE TITLE
Check box will be hidden If on property is true by default.

### ISSUE THREAD

**Issue by zhw511006** [Boris-Em/BEMCheckBox#2]
If set on property is true on ViewDidLoad method, when click on check box, it will be hidden. If on property is false by default, when click on check box, it's ok. I also set hideBox = NO, no effect! Please check it! Thanks!

**Comment by CoolestNerdIII** [comment]
I have encountered this issue too.

**Comment by nbfuhao** [comment]
Looks like if set the on property to true in `ViewDidLoad`, the `drawRect` method of the BEMCheckBox will be invoked later than the `drawOffBox` method. 
A force reload will work.

**Comment by Boris-Em** [comment]
Thank you for reporting this issue.
You're absolutely right @nbfuhao, this is what was causing it.
I just pushed a fix on the master branch. Let me know if everything works as expected and I'll close the bug.
Thanks again!

**Comment by zhw511006** [comment]
It works! Thx!

**Comment by Boris-Em** [comment]
Great, thanks @zhw511006 !
Closed as fixed with commit dc75191
