### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by hardikdevios** [Boris-Em/BEMCheckBox#20]
Any Good bits for Carthage?

**Comment by Boris-Em** [comment]
Hi @hardikdevios,
Honestly, I haven't taken the time to really look into Carthage. Considering its popularity, it's something that should definitely added to the library.

**Comment by hardikdevios** [comment]
@Boris-Em I am very much new in Carthage just started integration of All my pods to Carthage.Issue with Pods is that if you have too many Pods it will slow up your build time which is costly now a days.If i get proper time in weekends i will do Pull request for you. Buts its my humble request you support Carthage as so many good thing over Pods.

**Comment by hardikdevios** [comment]
#22 Here you go mate. Please merge it

**Comment by Boris-Em** [comment]
Thanks for your work @hardikdevios! The PR has been merged.
