### ISSUE TITLE
BEMCheckBox object cannot be an outlet in Swift

### ISSUE THREAD

**Issue by rubenjimenez** [Boris-Em/BEMCheckBox#24]
Hi,

I'm using your library and it's truly awesome, congrats =)

I'm suffering a little issue and perhaps you might help me. I've placed an UIView and changed its class to BEMCheckBox afterwards from Storyboard. Everything is running pretty well, but when I try to make an outlet from the BEMCheckBox object in Storyboard to my View Controller I'm getting the next 2 errors:

```
'weak' may only be applied to class and class-bound protocol types, not '<<error type>>'
Use of undeclared type 'BEMCheckBox'
```

This is the outlet:

```
@IBOutlet weak var taskCheckBox: BEMCheckBox!
```

I'm using Swift and I had to create a bridge. Any idea of what's happening?

**Comment by Boris-Em** [comment]
Hi @rubenjimenez,
Thanks for opening this issue, and the kind words =)
Have you tried creating a strong IBOutlet?
Also, could we take a look at your bridging header?

**Comment by spyroseth** [comment]
Hello @rubenjimenez,

You must first import BEMCheckbox in your Bridge header, then in your Swift file that uses the checkbox. After that connect your outlet and you are done.

**Comment by rubenjimenez** [comment]
Hi @Boris-Em @spyroseth,

Indeed, everything worked when I put

```
#import "BEMCheckBox.h"
```

in my bridging-header.h file.

Now I'm using it programmatically with no problem but I've got a doubt. How can I override the delegate methods within my Swift file? Do I have to mix Swift and Objective-C code? Or is there any way to override the method using Swift directly?

Thanks!

**Comment by Boris-Em** [comment]
Great to hear that you figured it out @rubenjimenez.
You can implement the delegate methods in Swift directly.  
Here is a very simple example:  
```swift
class ViewController: UIViewController, BEMCheckBoxDelegate {
    
    let checkbox = BEMCheckBox(frame: CGRectMake(0.0, 0.0, 50.0, 50.0))

    override func viewDidLoad() {
        super.viewDidLoad()
        checkbox.delegate = self
        self.view.addSubview(checkbox)
    }

    func didTapCheckBox(checkBox: BEMCheckBox) {
        print("Did tap checkbox.")
    }
    
    func animationDidStopForCheckBox(checkBox: BEMCheckBox) {
        print("Checkbox animation did stop.")
    }
}
```
Let me know if that answers your question!

**Comment by rubenjimenez** [comment]
It worked like a charm, thank you very much @Boris-Em

I really appreciate fast and reliable help =)

**Comment by Boris-Em** [comment]
Glad to hear that @rubenjimenez!
Closing this issue as fixed.
