### ISSUE TITLE
iOS 10 Warning: Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'BEMCheckBox *const __strong'

### ISSUE THREAD

**Issue by Signoo** [Boris-Em/BEMCheckBox#25]
I've just downloaded XCode 8.2 and the compiler returns this warning:
`Assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'BEMCheckBox *const __strong'`
In each line where you set the delegate inside the `addOnAnimation` function.

I just found it out and posted it here, if I found a solution i'll let you know

**Comment by Signoo** [comment]
Ok actually it was easy to fix, in `BEMCheckBox.h` I just had to replace the line:
`IB_DESIGNABLE @interface BEMCheckBox : UIView `
with:
`IB_DESIGNABLE @interface BEMCheckBox : UIView <CAAnimationDelegate>`

**Comment by Boris-Em** [comment]
HI @Signoo,
Would you mind submitting a pull request with your work?
Thank you!

**Comment by Signoo** [comment]
Hi @Boris-Em 
I've created the pull request, It's my first one so hopefully I did nothing wrong :)

Btw thanks for this awesome library!

**Comment by Boris-Em** [comment]
Closed as fixed with #30. Thank you for opening this issue and fixing it @Signoo!

**Comment by iTofu** [comment]
Thanks for @Signoo ! It works for me!

**Comment by abj001** [comment]
Thanks for @Signoo ! It works for me!
