### ISSUE TITLE
Please do not use @import

### ISSUE THREAD

**Issue by gelldur** [Boris-Em/BEMCheckBox#27]
http://stackoverflow.com/questions/32555710/xcode-modules-enabled-in-settings-but-still-cant-use-import

**Comment by Boris-Em** [comment]
Closed as fixed with commit 4e49b896aadb4305fc87bf78466edc56bab0a8ad.

**Comment by Emailrus** [comment]
Not sure, but I think you can fix it this way

```
#if __has_feature(modules)
    @import Foundation;
#else
    #import <Foundation/Foundation.h>
#endif
```

**Comment by Boris-Em** [comment]
Thanks for your contribution @Emailrus. 
Would you mind doing some testing and if it works correctly submitting a pull request?

**Comment by Emailrus** [comment]
Well, I don't have any Objective-C++ projects, I just saw this pattern used in Mogenerator utility
