### ISSUE TITLE
how to add two or more checkboxs?

### ISSUE THREAD

**Issue by subhash08** [Boris-Em/BEMCheckBox#3]
how to implement two or more checkbox in one viewcontroller, when one of them is checked then all other have to be unchecked automatically  ?
any help @Boris-Em ?

**Comment by Boris-Em** [comment]
Hi @subhash08,
Thank you for your interest in **BEMCheckBox**.
You can just instantiate different instances of the checkbox. For example, programatically you could do something like that:
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];

    BEMCheckBox *myCheckBox = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 50, 50)];
    [self.view addSubview:myCheckBox];
    
    BEMCheckBox *mySecondCheckBox = [[BEMCheckBox alloc] initWithFrame:CGRectMake(100, 100, 50, 50)];
    [self.view addSubview:mySecondCheckBox];
}
```
Of course, the same could be done in IB.
Let me know if you need more help!

**Comment by subhash08** [comment]
@Boris-Em , please reOpen this issue.
Yes, I already implemented three checkboxes  programmatically that is not a issue.
The main problem is , how to manage if  one of them is checked then all other have to be unchecked automatically .
help needed.

**Comment by mythodeia** [comment]
@subhash08 you can use the [delegate](https://github.com/Boris-Em/BEMCheckBox#delegate) to achieve what you want

**Comment by subhash08** [comment]
@mythodeia I want to achive, if one of them checkox is checked then allother have to be unchecked automatically.
yes, i used delegate method.

**Comment by mythodeia** [comment]
I think on the delegate method you should write that manually.

**Comment by subhash08** [comment]
@mythodeia , there is not any method to get check-box is checked or not.
that's why all problem occurred .

**Comment by mythodeia** [comment]
yes you can do it...
```
- (void)didTapCheckBox:(BEMCheckBox *)checkBox{
    NSLog(@"%d",checkBox.on);
}
```

**Comment by subhash08** [comment]
i used it like below, please check ...

    - (void)didTapCheckBox:(BEMCheckBox*)checkBox
     {
        if (checkBox == checkbox  ){
            self.scroll.backgroundColor = [UIColor blueColor];
            checkbox1.on = NO;
       // [self.checkbox1 reload];
                                          }
       if(checkBox == checkbox1){
           self.scroll.backgroundColor = [UIColor redColor];
           checkbox.on = NO;
        //[self.checkbox1 reload];
                                }
      }


but no response

**Comment by mythodeia** [comment]
```
- (void)didTapCheckBox:(BEMCheckBox *)checkBox{
   // only do this when checkbox is checkbox1 and value is true
   if (checkBox1.on && checkBox == checkBox1) {
        // if checkbox1 is on then uncheck all the others
        checkBox2.on = NO;
        checkBox3.on = NO;
    }
}
```

**Comment by subhash08** [comment]
actually problem is solved now.
with  a single line code that is

     checkBox.delegate = self;
that was i missed.

**Comment by mythodeia** [comment]
i thought that you had that line. :P

**Comment by subhash08** [comment]
sorry, for this stupid question, with out check my own code.

**Comment by Boris-Em** [comment]
Glad you figured things out @subhash08.
To fix the warning, are you sure that your view controller conforms to the `BEMCheckBoxDelegate` protocol?

**Comment by subhash08** [comment]
I do it , but on viewcontroller.m file not on viewcontroller.h . Is it matters?

**Comment by i-am-chris** [comment]
Hi, how do you call the checkbox specifically? How do you define it in viewdidload ? as i have 3 different BMCHeckbox-es with different values to put on.

**Comment by Boris-Em** [comment]
Hi @i-am-chris, 
Please open a new issue with more details about your problem, since it doesn't seem related to this issue.
Thank you!
