### ISSUE TITLE
Podspec update

### ISSUE THREAD

**Issue by Emailrus** [Boris-Em/BEMCheckBox#33]
Current version is 1.3.0, but latest available version on CocoaPods is only 1.2.1

**Comment by Boris-Em** [comment]
The only change between 1.2.1 and 1.3.0, is the support of Carthage. Since this doesn't impact anything for CocoaPods users, I didn't feel like it was necessary to update the pod.
Please let me know, if you think otherwise.

**Comment by Emailrus** [comment]
I guess it's fine, although 1.3.0 has some changes regarding imports and fix for objective-c++

**Comment by simonbromberg** [comment]
The podspec in this project is still out of date (and for some reason has .json as the file extension)
