### ISSUE TITLE
tags and multiple checkboxes

### ISSUE THREAD

**Issue by i-am-chris** [Boris-Em/BEMCheckBox#35]
What is the best scenario for this?

  30 checkboxes in 10 tableviewcells, 3 checkboxes in each cell.
  each defined with tags (a.tag = 101; b.tag = 201; c.tag = 301;) a,b,c are 
  every checkbox has a defined value (how can we achieve this ??)
     - Example: a.value = @"this is a value"; b.value = [NSDate new]; etc.

 Now, i want to get the value tapped on a checkbox when is checked or unchecked (.on event)
and to populate the checkboxes with data coming from a json file (matrix of checks?)

Any good idea on how to approach this?

Thanks.
Chris

**Comment by Boris-Em** [comment]
Hi @i-am-chris,
Do you create model objects from the json file you get?
You could use the method `didTapCheckBox:` of the [delegate](https://github.com/Boris-Em/BEMCheckBox#delegate), and then check the tag for example.

**Comment by i-am-chris** [comment]
`- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

     static NSString *simpleTableIdentifier = @"SimpleTableItemZZ";
     
     UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:simpleTableIdentifier];
     
     int checkTagM = 100;
     int checkTagA = 200;
     int checkTagE = 300;
     
     cell.textLabel.text = @"";
     
     BEMCheckBox *m = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
     BEMCheckBox *a = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
     BEMCheckBox *e = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
     UILabel *dayTXT  = [[UILabel alloc] initWithFrame:CGRectMake(10, 10, 100, cell.frame.size.height)];
     
     m.delegate = self;
     a.delegate = self;
     e.delegate = self;

     
     if (cell == nil) {
         cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:simpleTableIdentifier];
         //[cell.m removeFromSuperview];
     
      
     m.boxType =  BEMBoxTypeSquare;
     m.tintColor =[UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];;
     m.onCheckColor = [UIColor whiteColor];
     m.onTintColor= [UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];
     m.onFillColor =[UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];
     m.onAnimationType = BEMAnimationTypeStroke;
     m.offAnimationType = BEMAnimationTypeFill;
     m.animationDuration = 0.3;
         m.on = YES;
         
     a.boxType =  BEMBoxTypeSquare;
     a.tintColor =[UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];;
     a.onCheckColor = [UIColor whiteColor];
     a.onTintColor= [UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];
     a.onFillColor =[UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];
     a.offAnimationType = BEMAnimationTypeFill;
     a.animationDuration = 0.3;
         a.on = YES;
     
     e.boxType =  BEMBoxTypeSquare;
     e.tintColor =[UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];;
     e.onCheckColor = [UIColor whiteColor];
     e.onTintColor= [UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];
     e.onFillColor =[UIColor colorWithRed:0.15 green:0.93 blue:0.87 alpha:1];
     e.onAnimationType = BEMAnimationTypeStroke;
     e.offAnimationType = BEMAnimationTypeFill;
     e.animationDuration = 0.3;
         e.on = YES;
     
    
     //[e addTarget:self action:@selector(setAllEvenings:) forControlEvents:UIControlEventValueChanged];
     // [mSwitch addTarget:self action:@selector(setAllMornings:) forControlEvents:UIControlEventValueChanged];
     // [e addTarget:self action:@selector(getValue:) forControlEvents:UIControlEventTouchUpInside];

     NSLog(@"%ld:%ld:%ld",(long)m.tag,(long)a.tag,(long)e.tag);
     
     m.center = CGPointMake(cell.frame.size.width/4*1+cell.frame.size.height, cell.frame.size.height/2);
     a.center = CGPointMake(cell.frame.size.width/4*2+cell.frame.size.height, cell.frame.size.height/2);
     e.center = CGPointMake(cell.frame.size.width/4*3+cell.frame.size.height, cell.frame.size.height/2);
        
   
     
     [cell addSubview:m];
     [cell addSubview:a];
     [cell addSubview:e];
     
         
         
         dayTXT.font = appFontRegular(12);
         dayTXT.textAlignment = NSTextAlignmentRight;
         dayTXT.frame = CGRectMake(0, 0, 100, cell.frame.size.height);
         //dayTXT.backgroundColor = [UIColor redColor];
         
         [cell addSubview:dayTXT];

         
     }
     //dayTXT.tag = 121;
     m.tag = checkTagM + indexPath.row;
     a.tag = checkTagA + indexPath.row;
     e.tag = checkTagE + indexPath.row;
     _objectArray =  [_enumeratorul nextObject];
     NSLog(@"Zi: %@ = %@ ",[_daysOFDoom objectAtIndex:indexPath.row],@"");
     NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init]; [dateFormatter setDateFormat:@"EE dd"]; NSLog(@"The day of the week: %@", [dateFormatter stringFromDate:[_daysOFDoom objectAtIndex:indexPath.row]]); return cell; }`
// and my  other listener is: 

`- (void)didTapCheckBox:(BEMCheckBox *)checkBox{
    NSLog(@"you touched: %d,%ld",checkBox.on,(long)checkBox.tag);
}`


I want to have a day-value for each checkbox and then retrieve it via didTapCheckBox

**Comment by Boris-Em** [comment]
A few observations / questions:

 1. Why don't you do all of these initializations in the `if (cell == nil)` statement: 
  ```objective-c
   BEMCheckBox *m = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
   BEMCheckBox *a = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
   BEMCheckBox *e = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 30, 30)];
   UILabel *dayTXT  = [[UILabel alloc] initWithFrame:CGRectMake(10, 10, 100, cell.frame.size.height)];
```
 2. It doesn't seem like you're doing anything with `dayTXT`
 3. I'm not exactly sure what you mean by "day-value" in the following sentence: "I want to have a day-value for each checkbox and then retrieve it via didTapCheckBox"
 4. Would something like that work?
```objective-c
- (void)didTapCheckBox:(BEMCheckBox *)checkBox{
    NSDateFormatter *dateFormatter = [[NSDateFormatter alloc] init]; [dateFormatter setDateFormat:@"EE dd"];
    NSString *date = [dateFormatter stringFromDate:[_daysOFDoom objectAtIndex: checkTag]];
}
```
Note that I just use you should set the row as a tag for all of the checkboxes:
```objective-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
...
 m.tag = indexPath.row;
 a.tag = indexPath.row;
 e.tag = indexPath.row;
...
```

**Comment by i-am-chris** [comment]
1. because all the tags are dynamic. (it dep. of how many rows i have) so i've set each row to be a factor of 100. 
2. dayTXT - does not matter (was a test... to see a value for each time of day)
3. let's say i want a value to be set for each box. 
dayvalue = nsdate  (a date value for each box.) I want to pair a box with a set value. 

Here is what i want to achieve: 

![here](https://cloud.githubusercontent.com/assets/21122128/18485524/1b98c54e-79e5-11e6-9c38-068db8da9e44.jpg)

**Comment by danie11am** [comment]
It'll be easier to implement, more modular, and less error-prone for you, if you don't assign a unique ID to each checkbox. That won't be necessary. Instead, create a custom cell, within which you have a day value and 3 checkboxes. The cell implement the checkbox delegate protocol (i.e. the custom cell class implements `(void)didTapCheckBox:(BEMCheckBox *)checkBox`. It can then compare which checkbox was tapped, using if statements comparing with the 3 properties, then it can call another callback function to the table view controller to say what day and which time has been selected/unselected.

**Comment by Boris-Em** [comment]
Closing this question as fixed thanks to @danie11am's answer.
@i-am-chris, feel free to reopen this issue if you need more help!
