### ISSUE TITLE
Copy cat

### ISSUE THREAD

**Issue by rob-nash** [Boris-Em/BEMCheckBox#36]
This is a clone of https://github.com/Marxon13/M13Checkbox

**Comment by Boris-Em** [comment]
Hi @rob-nash,
This is actually the other way around. **M13Checkbox** has been updated and now looks suspiciously like **BEMCheckBox**. 
**M13Checkbox** has been rewritten in march 2016 with [this commit](https://github.com/Marxon13/M13Checkbox/commit/6262a5eaacd4c9d9d54bf482e95b3cfe49ab2fbd). This is when the project seem to just have become a Swift implementation of **BEMCheckBox**.  
I realized that a few month ago, and am not sure what to do about it. I actually am okay with it, although a little mention of BEMCheckBox on the readme would have been nice =)
Maybe I should open an issue on their board like you did?

**Comment by rob-nash** [comment]
Apologies. I thought it was the other way around. I have been raising issues on the other guys repo.

**Comment by Boris-Em** [comment]
No worries @rob-nash!
