### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by cesarmtz93** [Boris-Em/BEMCheckBox#37]
Will you consider to add radioButton option as well in the near future?

**Comment by Boris-Em** [comment]
Hi @cesarmtz93, we recently added a new feature called [group](https://github.com/Boris-Em/BEMCheckBox#group--radio-button-functionality).
If this is not what you wanted, please give us a more complete description of the behavior you're expecting, and we'll review it!
Thank you for your feedback =)

**Comment by cesarmtz93** [comment]
Hello @Boris-Em ! Thanks for the hard work on this function actually it's going to help my project a lot! 

I’m Sorry I wasn’t more clear on what i was looking for but currently I'm using [DLRadioButton github] (url), which is the function that i was talking about, the problem with this is that it isn't as awesome and pretty as your library and hope you could implement this, so i can have just your library! 


Thanks for paying attention to the need of the community! awesome job that you have made with this project!
