### ISSUE TITLE
Graphical problem while disabiling after an UIAlertController is shown

### ISSUE THREAD

**Issue by samuelrabini** [Boris-Em/BEMCheckBox#40]
Here you can download a video that shows the problem:
https://dl.dropboxusercontent.com/u/8581359/check_box_usage.mp4

Untill I show an UIAlertController, the behavior is correct, but as soon as I show it, the disabled animation brokes.

Here is the didTapCheckBox event:

```
-(void)didTapCheckBox:(id)sender {
    BEMCheckBox *checkBox = (BEMCheckBox*)sender;
    
    SpaceTargetInfoV2 *spaceTarget;
    for(SpaceTargetInfoV2 *st in self.spaceTargetListResponse.spaceTargetList) {
        if(st.idSpaceTarget == checkBox.tag) {
            spaceTarget = st;
        }
    }
    
    // if user wants to unbind check if it was the bind owner
    if(!checkBox.on) {
        if(spaceTarget.idUserBindOwner == [[[NSNumberFormatter alloc] init] numberFromString:[Util getIDUser]]) {
            // call the unbind
        }
        else {
            // alert user he cannot do that op
            UIAlertController * alert = [UIAlertController alertControllerWithTitle:[Util getLangValueForTag:@"geofenceUnbindNotAuthorized"]
                                                                            message:@""
                                                                     preferredStyle: UIAlertControllerStyleAlert];
            
            UIAlertAction *ok = [UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleCancel handler:^(UIAlertAction *action){}];
            [alert addAction:ok];
            
            [self presentViewController:alert animated:YES completion:nil];
            [self.tableView reloadData];
        }
    }
    else {
        
    }
}
```

Waiting for your replay.

Thanks in advance,
Samuel

**Comment by Boris-Em** [comment]
I'm guessing that this has to do with `[self.tableView reloadData];`.
I'm going to try to repro this bug when I find some time.
Would you mind sharing your `cellForRowAtIndexPath` method?

**Comment by samuelrabini** [comment]
Here it is:

`
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

    SpaceTargetTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"spaceTargetCell" forIndexPath:indexPath];
        
    SpaceTargetInfoV2 *spaceTarget = [self.spaceTargetListResponse.spaceTargetList objectAtIndex:indexPath.row];
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    cell.selectionStyle = UITableViewCellSelectionStyleNone;

    cell.spaceTargetName.text = spaceTarget.name;
    if([spaceTarget hasAlarm]) {
        [cell.spaceTargetArmedImage setImage:[UIImage imageNamed:@"bell_enabled"]];
    }
    else {
        [cell.spaceTargetArmedImage setImage:[UIImage imageNamed:@"bell_disabled"]];
    }
    
    BEMCheckBox *spaceTargetCheckBox = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 35, 35)];
    spaceTargetCheckBox.on = [spaceTarget isBound];
    spaceTargetCheckBox.delegate = self;
    spaceTargetCheckBox.tag = spaceTarget.idSpaceTarget;
    //spaceTargetCheckBox.enabled = (spaceTarget.idUserBindOwner == [[[NSNumberFormatter alloc] init] numberFromString:[Util getIDUser]]);
    
    [spaceTargetCheckBox setOnAnimationType:BEMAnimationTypeOneStroke];
    [cell.spaceTargetConnectedCheckBox addSubview:spaceTargetCheckBox];
    
    return cell;
}
`

thanks

**Comment by Boris-Em** [comment]
It looks like you're adding a new checkbox every time the method gets called (even though the cell might be reused, and therefore already has a checkbox).
```objective-c
[cell.spaceTargetConnectedCheckBox addSubview:spaceTargetCheckBox];
```

**Comment by samuelrabini** [comment]
Hi try to refactor a little the code this way:
- I added the IBOutlet to the SpaceTargetViewCell:
`@property (nonatomic, retain) IBOutlet BEMCheckBox *spaceTargetConnectedCheckBox;`
- in the storyboard I set the UIView as instance of BEMCheckBox and I connected it to the IBOutlet 

<img width="937" alt="storyboard" src="https://cloud.githubusercontent.com/assets/6568030/19510534/f9aea992-95e3-11e6-9917-35949b108b85.png">

- I added a BEMCheckBox to the SpaceTargetInfoV2 class
- then I tried 2 codes for the `cellForRowAtIndexPath` method:

```
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

    SpaceTargetTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"spaceTargetCell" forIndexPath:indexPath];
        
    SpaceTargetInfoV2 *spaceTarget = [self.spaceTargetListResponse.spaceTargetList objectAtIndex:indexPath.row];
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    cell.selectionStyle = UITableViewCellSelectionStyleNone;

    cell.spaceTargetName.text = spaceTarget.name;
    if([spaceTarget hasAlarm]) {
        [cell.spaceTargetArmedImage setImage:[UIImage imageNamed:@"bell_enabled"]];
    }
    else {
        [cell.spaceTargetArmedImage setImage:[UIImage imageNamed:@"bell_disabled"]];
    }
    
    // add checkboxes
    NSLog(@"Check box for space target %@ is bound: %i", spaceTarget.name, spaceTarget.spaceTargetCheckBox.on);
    cell.spaceTargetConnectedCheckBox = [[BEMCheckBox alloc] initWithFrame:CGRectMake(0, 0, 35, 35)];
    cell.spaceTargetConnectedCheckBox.on = spaceTarget.spaceTargetCheckBox.on;
    cell.spaceTargetConnectedCheckBox.tag = spaceTarget.spaceTargetCheckBox.tag;
    [cell.spaceTargetConnectedCheckBox setOnAnimationType:BEMAnimationTypeOneStroke];

    //spaceTarget.spaceTargetCheckBox.delegate = self;
    //[self.spaceTargetConnectedCheckBox addSubview:self.spaceTargetCheckBox];
    return cell;
}
```

and
```

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {

    SpaceTargetTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"spaceTargetCell" forIndexPath:indexPath];
        
    SpaceTargetInfoV2 *spaceTarget = [self.spaceTargetListResponse.spaceTargetList objectAtIndex:indexPath.row];
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    cell.selectionStyle = UITableViewCellSelectionStyleNone;

    cell.spaceTargetName.text = spaceTarget.name;
    if([spaceTarget hasAlarm]) {
        [cell.spaceTargetArmedImage setImage:[UIImage imageNamed:@"bell_enabled"]];
    }
    else {
        [cell.spaceTargetArmedImage setImage:[UIImage imageNamed:@"bell_disabled"]];
    }
    
    // add checkboxes
    NSLog(@"Check box for space target %@ is bound: %i", spaceTarget.name, spaceTarget.spaceTargetCheckBox.on);
    cell.spaceTargetConnectedCheckBox = spaceTarget.spaceTargetCheckBox;

    //spaceTarget.spaceTargetCheckBox.delegate = self;
    //[self.spaceTargetConnectedCheckBox addSubview:self.spaceTargetCheckBox];
    return cell;
}
```
but for both this the result is this one:

<img width="225" alt="preview" src="https://cloud.githubusercontent.com/assets/6568030/19510543/0aa47984-95e4-11e6-9aaa-1b4ae336fead.png">

I'll do some more test during the day.

Regards,
Samuel

**Comment by Boris-Em** [comment]
Hi @samuelrabini,
The second implementation you shared is closer to what need to be done here.
On the screenshot your posted, none of the checkboxes are set to on. Does that happen no even if you tap on them?

**Comment by samuelrabini** [comment]
They are mi set in even if the boolean I used is true. If I tap they correctly switch to on, but the even is not fired

**Comment by Boris-Em** [comment]
I see. A couple of things here:
- The delagate is probably not set correctly. I see that this line is commented:
```objective-c
//spaceTarget.spaceTargetCheckBox.delegate = self;
```
- You're going to need to keep track of the state of each checkboxes. When the cells are being reused, you need to set them to the correct state.

**Comment by samuelrabini** [comment]
I solved the problem remove all subview from the UIView before adding the new BEMCheckBox to the cell:

```
[[cell.spaceTargetConnectedCheckBoxView subviews] makeObjectsPerformSelector:@selector(removeFromSuperview)];
        [cell.spaceTargetConnectedCheckBoxView addSubview:spaceTargetCheckBox];
```

Regards,
Samuel

**Comment by Boris-Em** [comment]
Glad you figured it out @samuelrabini!
