### ISSUE TITLE
Podfile

### ISSUE THREAD

**Issue by cesarmtz93** [Boris-Em/BEMCheckBox#45]
There new changes weren't brought through cocoa pods, maybe theres a need to update the pod file?

**Comment by Boris-Em** [comment]
Yep, the pod needs to be updated.

**Comment by VivienGiraud** [comment]
When will it be updated?
Even setting tag in pod doesn't works:
`pod 'BEMCheckBox', git: 'https://github.com/Boris-Em/BEMCheckBox', tag: '1.4.0'`
It will install version 1.0.0 :/

**Comment by OyaSaid** [comment]
When will the pod file be updates because it still doesn't have the features mentioned -.- .

**Comment by Boris-Em** [comment]
Hi there @OyaSaid & @VivienGiraud. This should be fixed. Please try`pod 'BEMCheckBox', '1.4'` and report back to me!
Thanks!

**Comment by OyaSaid** [comment]
Still not working :(

**Comment by Boris-Em** [comment]
Hmm this is strange @OyaSaid, it is working for me. Would you mind posting your podfile here?

**Comment by Boris-Em** [comment]
Closed as fixed.
