### ISSUE TITLE
if i want the frame to be bigger than the circle,i can not.

### ISSUE THREAD

**Issue by dominatinglj** [Boris-Em/BEMCheckBox#5]
i think you should write a method or an attribute to change the size of the circle.

**Comment by ptseng** [comment]
Agree

**Comment by mtide** [comment]
Hello, I got an error: 
Failed to set (lineWidth) user defined inspected property on (UIView): [<UIView 0x7fddea73a000> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key lineWidth.

I initialize the BECheckBox using Interface Builder.

**Comment by Boris-Em** [comment]
Hi @mtide,
Is the error you mention related to the new feature discussed in this issue?
If not, please open a separate issue for the bug you found. Thank you!

**Comment by mtide** [comment]
Hi @Boris-Em,
So sorry about that. It's a new issue, I will open a separate isseue for it. 
Thank you very much!

**Comment by xinsight** [comment]
Is the desire to change the size of the circle because when the circle is small the control is too small to tap? If so, this was addressed in #19. You size the control however you want, and the tap area will always be 44x44pt.

**Comment by Boris-Em** [comment]
Closed as fixed with commit 257da07.
