### ISSUE TITLE
set BEMCheckBox on property to NO

### ISSUE THREAD

**Issue by LargeShrimp** [Boris-Em/BEMCheckBox#50]
When i set BEMCheckBox on property to NO, And it's value is No ,But the view is not refreshed .

**Comment by Boris-Em** [comment]
This is the intended behavior. To refresh the checkbox, please use the [`reload`](https://github.com/Boris-Em/BEMCheckBox#reloading) method.

**Comment by LargeShrimp** [comment]
@Boris-Em ok, Thanks.
