### ISSUE TITLE
Using this view with another view like image or label

### ISSUE THREAD

**Issue by sam-moshenko** [Boris-Em/BEMCheckBox#53]
Hi, this BEMCheckBox class is good. But there is one problem, it does not support another view hanging near. I think the most common use of this class would be with some image or text near by. And users sometimes would prefer this view to be somehow highlighted when the checkbox is checked.
Here is a little class that does that with image and your class, may be someone could see it useful 
[gist link](https://gist.github.com/sam-moshenko/eecf146668a0e0eea4c192f31e7e3d7d)

**Comment by Boris-Em** [comment]
Thank you for your contribution @sam-moshenko !
