### ISSUE TITLE
Assigning Delegate

### ISSUE THREAD

**Issue by emtjoshhart** [Boris-Em/BEMCheckBox#56]
If this checbox is a property of a UITableViewCell how do you recieve the delegate method of didTapOn?  Perhaps i'm doing this wrong, but i've tried to assign the delegate within my custom tableviewcell and within my cellForRowAtIndexPath inside my tableViewController and still that delegate method does not fire when tapping on the checkbox.

**Comment by Boris-Em** [comment]
Hi @emtjoshhart,
Setting the delegate inside cell should work the same way. 
Could we take a look at your `cellForRowAtIndexPath` implementation?

**Comment by hartjosh** [comment]
`
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    VehiclesTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"vehicleCell" forIndexPath:indexPath];
    FIRDataSnapshot *snapshot = (self.firebasePenniesArray)[indexPath.row];
    if (isSearching) {
        FIRDataSnapshot *snapshot = (self.filteredContentList)[indexPath.row];
        cell.postKey = [snapshot valueForKey:@"postId"];
        NSString *verifiedAmount = [snapshot valueForKey:@"likesCount"];
        if (verifiedAmount == nil || verifiedAmount == 0) {
            cell.verifiedByLabel.text = [NSString stringWithFormat:@"Verified by 0 members"];
        }
        if (verifiedAmount > 0) {
            cell.verifiedByLabel.text = [NSString stringWithFormat:@"Verified by %@ members", verifiedAmount];
        }
        [self determineLikeCountColorWithSnapshot:snapshot inCell:cell];
        NSString *sku = [snapshot valueForKey:@"SKU"];
        NSString *itemName = [snapshot valueForKey:@"Description"];

        NSString *url = [snapshot valueForKey:@"itemImage"];
        [self setPostImageWithCell:cell withURL:url];

        cell.pennyLabel.attributedText = [self setAttributedTextFor:itemName andFor:sku];
        
        return cell;
    }

    cell.postKey = [snapshot valueForKey:@"postId"];
    NSString *verifiedAmount = [snapshot valueForKey:@"likesCount"];
    if (verifiedAmount == nil || verifiedAmount == 0) {
        cell.verifiedByLabel.text = [NSString stringWithFormat:@"Verified by 0 members"];
    }
    if (verifiedAmount > 0) {
        cell.verifiedByLabel.text = [NSString stringWithFormat:@"Verified by %@ members", verifiedAmount];
    }
    NSString *sku = [snapshot valueForKey:@"SKU"];
    NSString *itemName = [snapshot valueForKey:@"Description"];

    NSString *url = [snapshot valueForKey:@"itemImage"];
    [self setPostImageWithCell:cell withURL:url];
    [self determineLikeCountColorWithSnapshot:snapshot inCell:cell];
    cell.pennyLabel.attributedText = [self setAttributedTextFor:itemName andFor:sku];
    return cell;
}

- (void)determineLikeCountColorWithSnapshot:(FIRDataSnapshot *)snapshot inCell:(VehiclesTableViewCell *)cell {
    NSString *userID = [self getUid];
    if ([[snapshot valueForKey:@"likes"] valueForKey:userID]) {
        cell.checkBox.on = YES;
    } else {
        cell.checkBox.on = NO;
    }
}`

**Comment by Boris-Em** [comment]
I'm not sure exactly what you mean by "attach an action", but`BEMCheckBox` only supports delegate methods to get feedback.

**Comment by hartjosh** [comment]
Okay, you can close this then, I needed the checkbox to call the action within the UITableViewCell implementation.  By attaching an action i meant creating an action IBOutlet that gets called on touchUpInside.  I appreciate all of your hard work with creating such a valuable resource!  Thanks!

**Comment by Boris-Em** [comment]
You're welcome @hartjosh!
