### ISSUE TITLE
Bug with setting colors and animation.

### ISSUE THREAD

**Issue by AlexKarpov** [Boris-Em/BEMCheckBox#59]
When I tried to change colors with `setOnTintColor:` and `setOnCheckColor:` and then change state with `setOn:(BOOL)on animated:(BOOL)animated`, the check box changed its state without animation.

**Comment by Boris-Em** [comment]
Hi @AlexKarpov,

I couldn't repro your issue. Are you sure that you're not using the same color for the on and off state?
I'm closing this issue for now since I couldn't repro it. If you're still running into it, please reopen it!
