### ISSUE TITLE
When checkbox is "on" by default, unchecking it makes the box disappear

### ISSUE THREAD

**Issue by A1exandre** [Boris-Em/BEMCheckBox#6]
This happens when I :
- Set default to on in interface builder
- set default to on in viewdidload with  button.on = true
- set default to on in viewdidlaod with button.setOn(true, animated: true)

The code I use to uncheck the box is :
button.setOn(false, animated:true)

![bug bem checkbox](https://cloud.githubusercontent.com/assets/15021331/11076993/cbc5dfae-87cb-11e5-8471-a1f1bb17a3d1.gif)

**Comment by Boris-Em** [comment]
Hi @A1exandre,

I think that this bug should be fixed with the version of the library on the master branch.
Currently the CocoaPods is a little bit behind.
