### ISSUE TITLE
give select all functionality to checkbox

### ISSUE THREAD

**Issue by jadhavabh** [Boris-Em/BEMCheckBox#63]
depend on main checkbox selection, remaining checkbox on and off.
how to assign checkbox array to your checkbox.group

**Comment by Boris-Em** [comment]
Hi @jadhavabh,

Thank you for opening this issue. You can find an example explaning how to assign an array of checkboxes to a group.
https://github.com/Boris-Em/BEMCheckBox#group--radio-button-functionality

Let me know if that doesn't solve your issue!
