### ISSUE TITLE
IBDesignable Failed in Swift

### ISSUE THREAD

**Issue by BoomaRajan** [Boris-Em/BEMCheckBox#67]
HI All,

I have bridge with Swift.  Still ,IBDesignable build Failed.
<img width="254" alt="screen shot 2017-11-08 at 7 08 18 am" src="https://user-images.githubusercontent.com/13272421/32548794-e8c13c8a-c454-11e7-929d-bcfe8acd8c7b.png">
 NO target found containing the source files BEMCheckBox.Make Sure the one files are in the target
Please provide me some input on this

**Comment by Boris-Em** [comment]
Hi @BoomaRajan,
I just tried and didn't run into this problem. Did you get to fix it?

**Comment by BoomaRajan** [comment]
Thanks. yes.
