### ISSUE TITLE
Interface Builder - Failed to load designables from path (null)

### ISSUE THREAD

**Issue by narlei** [Boris-Em/BEMCheckBox#7]
Interface Builder - Failed to load designables from path (null)
Using Cocoapods, this error is showing.

**Comment by ValentinDenis** [comment]
Same for me, with and without cocoapods

**Comment by Boris-Em** [comment]
Hi there, this is a known bug. See [here](https://github.com/glaszig/SZTextView/issues/37) and [here](http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables).
You can try adding `use_frameworks!` to your pod file.
Please note that even though you get an error, you can still compile and everything should work as expected.
Thank you for opening this issue!
