### ISSUE TITLE
Animation is very fast

### ISSUE THREAD

**Issue by BoomaRajan** [Boris-Em/BEMCheckBox#71]
Hi All,
When I use the didTap() the animation is fast. I want to slow down the check mark tick process. I have set the animation duration ,but still not working

**Comment by Boris-Em** [comment]
Hi @BoomaRajan,

Thank you for opening this issue. Do you mean that the delegate method `didTapCheckBox:` gets called immediately, even though you change the animation duration?

**Comment by BoomaRajan** [comment]
Hi Team,
Yes. I would have save the data into CoreData. Which calls the insert of NSFetchResultController. After removing the code  from the **didTapCheckBox:**.The animation duration worked fine.       

**Solution to my issue.** 
I have moved my **save code** in  animationDidStop(for checkBox: BEMCheckBox):

Thanks for your reply.
