### ISSUE TITLE
swift

### ISSUE THREAD

**Issue by rotemdoron** [Boris-Em/BEMCheckBox#8]
cant seem to get it to work with swift, the import in the bridging header is fine but it will not work when i try to instantiate a BEMCheckBox object, anyone got an idea?

**Comment by cph2117** [comment]
You're going to need to import into bridging header.  Did you do that? Mine works, but it's highly pixelated...

**Comment by cph2117** [comment]
so obviously i can't use

**Comment by Boris-Em** [comment]
Hi @rotemdoron and @cph2117,
The project should work in Swift as @cph2117 mentioned.
Could you please share a little bit more about your pixelization issue @cph2117 ?
I don't seem to have this kind of issue with Swift.

**Comment by cph2117** [comment]
@Boris-Em , I think this might be a problem on my end.  I'll look into it further.
