### ISSUE TITLE
Won't animate with setOn method on iOS 12

### ISSUE THREAD

**Issue by melakamc** [Boris-Em/BEMCheckBox#85]
Tickbox animation doesn't work on iOS 12 anymore 

> checkBox.setOn(true, animated: true)

**Comment by nrbrook** [comment]
Fixed in https://github.com/Boris-Em/BEMCheckBox/pull/90

**Comment by danielgindi** [comment]
Seems to be okay in the Swift version too :-) (#93)

**Comment by Boris-Em** [comment]
Closed as fixed with https://github.com/Boris-Em/BEMCheckBox/pull/95.
