### ISSUE TITLE
Change the TintColor more than once

### ISSUE THREAD

**Issue by Signoo** [Boris-Em/BEMCheckBox#9]
I need to change the TintColor of the checkbox if the user hasn't checked it, I tried with:
[_pCheckBox setTintColor:[UIColor redColor]];
But the color doesn't change, the checkbox keeps the first color I had set using the setTintColor method.
Am I doing something wrong?

**Comment by Boris-Em** [comment]
Hi @Signoo,
Thank you for opening this issue. This is indeed a bug. The check box's tint color doesn't get set when using the setter method for some reason.
Using the property should work though.
```objective-c
 _pCheckBox.tintColor = [UIColor redColor];
```

Good catch!

**Comment by Boris-Em** [comment]
Hi @Signoo,
Thank you for opening this issue.
The check box doesn't get redrawn when calling `setTintColor:`. This means that you either need to call `reload` after setting the tint color, or you need to set it before adding the check box to your view (either in IB or in code).
Let me know if you need more info!

**Comment by Boris-Em** [comment]
Fixed with 6169686cba532b9586bb569dfb9ee33cf185d6ba.

**Comment by Signoo** [comment]
Hi @Boris-Em , I've used the reload method and it worked! Thanks a lot! :)
